apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-platform
  namespace: hello-platform
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    # Certificate ARN injected by CI/CD (self-signed via ACM)
    alb.ingress.kubernetes.io/certificate-arn: "<ACM_CERT_ARN>"
    # WAF ARN injected by CI/CD from terraform output waf_web_acl_arn
    alb.ingress.kubernetes.io/wafv2-acl-arn: "<WAF_WEB_ACL_ARN>"
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-platform
                port:
                  number: 80
