apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-platform
  namespace: hello-platform
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    # WAF ARN injected by CI/CD from terraform output waf_web_acl_arn
    alb.ingress.kubernetes.io/wafv2-acl-arn: "<WAF_WEB_ACL_ARN>"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-platform
                port:
                  number: 80
