apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-platform
  namespace: hello-platform
  annotations:
    # Populated by CI/CD from: terraform output -raw app_role_arn
    # GKE equivalent: iam.gke.io/gcp-service-account=<GSA_EMAIL>
    eks.amazonaws.com/role-arn: "<APP_ROLE_ARN>"
